//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ipca.pt/", ConfigurationName="ServiceReferenceAddGestorWsAsync.AddGestorWsSoap")]
    public interface AddGestorWsSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://ipca.pt/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ipca.pt/HelloWorld", ReplyAction="*")]
        Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.HelloWorldResponse HelloWorld(Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://ipca.pt/HelloWorld", ReplyAction="*")]
        System.IAsyncResult BeginHelloWorld(Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.HelloWorldRequest request, System.AsyncCallback callback, object asyncState);
        
        Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.HelloWorldResponse EndHelloWorld(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ipca.pt/CalcularSoma", ReplyAction="*")]
        int CalcularSoma(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://ipca.pt/CalcularSoma", ReplyAction="*")]
        System.IAsyncResult BeginCalcularSoma(int x, int y, System.AsyncCallback callback, object asyncState);
        
        int EndCalcularSoma(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name emailGestor from namespace http://ipca.pt/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ipca.pt/RegistarGestorBD", ReplyAction="*")]
        Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorBDResponse RegistarGestorBD(Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorBDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://ipca.pt/RegistarGestorBD", ReplyAction="*")]
        System.IAsyncResult BeginRegistarGestorBD(Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorBDRequest request, System.AsyncCallback callback, object asyncState);
        
        Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorBDResponse EndRegistarGestorBD(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name email from namespace http://ipca.pt/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ipca.pt/RegistarGestorUsingAPI", ReplyAction="*")]
        Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorUsingAPIResponse RegistarGestorUsingAPI(Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorUsingAPIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://ipca.pt/RegistarGestorUsingAPI", ReplyAction="*")]
        System.IAsyncResult BeginRegistarGestorUsingAPI(Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorUsingAPIRequest request, System.AsyncCallback callback, object asyncState);
        
        Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorUsingAPIResponse EndRegistarGestorUsingAPI(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://ipca.pt/", Order=0)]
        public Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://ipca.pt/", Order=0)]
        public Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ipca.pt/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistarGestorBDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistarGestorBD", Namespace="http://ipca.pt/", Order=0)]
        public Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorBDRequestBody Body;
        
        public RegistarGestorBDRequest() {
        }
        
        public RegistarGestorBDRequest(Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorBDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ipca.pt/")]
    public partial class RegistarGestorBDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string emailGestor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string passwordGestor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string emailAdmin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string passwordAdmin;
        
        public RegistarGestorBDRequestBody() {
        }
        
        public RegistarGestorBDRequestBody(string emailGestor, string passwordGestor, string emailAdmin, string passwordAdmin) {
            this.emailGestor = emailGestor;
            this.passwordGestor = passwordGestor;
            this.emailAdmin = emailAdmin;
            this.passwordAdmin = passwordAdmin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistarGestorBDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistarGestorBDResponse", Namespace="http://ipca.pt/", Order=0)]
        public Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorBDResponseBody Body;
        
        public RegistarGestorBDResponse() {
        }
        
        public RegistarGestorBDResponse(Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorBDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ipca.pt/")]
    public partial class RegistarGestorBDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RegistarGestorBDResult;
        
        public RegistarGestorBDResponseBody() {
        }
        
        public RegistarGestorBDResponseBody(bool RegistarGestorBDResult) {
            this.RegistarGestorBDResult = RegistarGestorBDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistarGestorUsingAPIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistarGestorUsingAPI", Namespace="http://ipca.pt/", Order=0)]
        public Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorUsingAPIRequestBody Body;
        
        public RegistarGestorUsingAPIRequest() {
        }
        
        public RegistarGestorUsingAPIRequest(Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorUsingAPIRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ipca.pt/")]
    public partial class RegistarGestorUsingAPIRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public RegistarGestorUsingAPIRequestBody() {
        }
        
        public RegistarGestorUsingAPIRequestBody(string email, string password) {
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistarGestorUsingAPIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistarGestorUsingAPIResponse", Namespace="http://ipca.pt/", Order=0)]
        public Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorUsingAPIResponseBody Body;
        
        public RegistarGestorUsingAPIResponse() {
        }
        
        public RegistarGestorUsingAPIResponse(Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorUsingAPIResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ipca.pt/")]
    public partial class RegistarGestorUsingAPIResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RegistarGestorUsingAPIResult;
        
        public RegistarGestorUsingAPIResponseBody() {
        }
        
        public RegistarGestorUsingAPIResponseBody(string RegistarGestorUsingAPIResult) {
            this.RegistarGestorUsingAPIResult = RegistarGestorUsingAPIResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AddGestorWsSoapChannel : Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.AddGestorWsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalcularSomaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CalcularSomaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistarGestorBDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RegistarGestorBDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistarGestorUsingAPICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RegistarGestorUsingAPICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddGestorWsSoapClient : System.ServiceModel.ClientBase<Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.AddGestorWsSoap>, Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.AddGestorWsSoap {
        
        private BeginOperationDelegate onBeginHelloWorldDelegate;
        
        private EndOperationDelegate onEndHelloWorldDelegate;
        
        private System.Threading.SendOrPostCallback onHelloWorldCompletedDelegate;
        
        private BeginOperationDelegate onBeginCalcularSomaDelegate;
        
        private EndOperationDelegate onEndCalcularSomaDelegate;
        
        private System.Threading.SendOrPostCallback onCalcularSomaCompletedDelegate;
        
        private BeginOperationDelegate onBeginRegistarGestorBDDelegate;
        
        private EndOperationDelegate onEndRegistarGestorBDDelegate;
        
        private System.Threading.SendOrPostCallback onRegistarGestorBDCompletedDelegate;
        
        private BeginOperationDelegate onBeginRegistarGestorUsingAPIDelegate;
        
        private EndOperationDelegate onEndRegistarGestorUsingAPIDelegate;
        
        private System.Threading.SendOrPostCallback onRegistarGestorUsingAPICompletedDelegate;
        
        public AddGestorWsSoapClient() {
        }
        
        public AddGestorWsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddGestorWsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddGestorWsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddGestorWsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<HelloWorldCompletedEventArgs> HelloWorldCompleted;
        
        public event System.EventHandler<CalcularSomaCompletedEventArgs> CalcularSomaCompleted;
        
        public event System.EventHandler<RegistarGestorBDCompletedEventArgs> RegistarGestorBDCompleted;
        
        public event System.EventHandler<RegistarGestorUsingAPICompletedEventArgs> RegistarGestorUsingAPICompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.HelloWorldResponse Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.AddGestorWsSoap.HelloWorld(Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.HelloWorldRequest inValue = new Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.HelloWorldRequest();
            inValue.Body = new Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.HelloWorldRequestBody();
            Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.HelloWorldResponse retVal = ((Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.AddGestorWsSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.AddGestorWsSoap.BeginHelloWorld(Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.HelloWorldRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHelloWorld(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.HelloWorldRequest inValue = new Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.HelloWorldRequest();
            inValue.Body = new Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.HelloWorldRequestBody();
            return ((Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.AddGestorWsSoap)(this)).BeginHelloWorld(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.HelloWorldResponse Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.AddGestorWsSoap.EndHelloWorld(System.IAsyncResult result) {
            return base.Channel.EndHelloWorld(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndHelloWorld(System.IAsyncResult result) {
            Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.HelloWorldResponse retVal = ((Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.AddGestorWsSoap)(this)).EndHelloWorld(result);
            return retVal.Body.HelloWorldResult;
        }
        
        private System.IAsyncResult OnBeginHelloWorld(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginHelloWorld(callback, asyncState);
        }
        
        private object[] OnEndHelloWorld(System.IAsyncResult result) {
            string retVal = this.EndHelloWorld(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHelloWorldCompleted(object state) {
            if ((this.HelloWorldCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        public void HelloWorldAsync(object userState) {
            if ((this.onBeginHelloWorldDelegate == null)) {
                this.onBeginHelloWorldDelegate = new BeginOperationDelegate(this.OnBeginHelloWorld);
            }
            if ((this.onEndHelloWorldDelegate == null)) {
                this.onEndHelloWorldDelegate = new EndOperationDelegate(this.OnEndHelloWorld);
            }
            if ((this.onHelloWorldCompletedDelegate == null)) {
                this.onHelloWorldCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHelloWorldCompleted);
            }
            base.InvokeAsync(this.onBeginHelloWorldDelegate, null, this.onEndHelloWorldDelegate, this.onHelloWorldCompletedDelegate, userState);
        }
        
        public int CalcularSoma(int x, int y) {
            return base.Channel.CalcularSoma(x, y);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginCalcularSoma(int x, int y, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCalcularSoma(x, y, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndCalcularSoma(System.IAsyncResult result) {
            return base.Channel.EndCalcularSoma(result);
        }
        
        private System.IAsyncResult OnBeginCalcularSoma(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int x = ((int)(inValues[0]));
            int y = ((int)(inValues[1]));
            return this.BeginCalcularSoma(x, y, callback, asyncState);
        }
        
        private object[] OnEndCalcularSoma(System.IAsyncResult result) {
            int retVal = this.EndCalcularSoma(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCalcularSomaCompleted(object state) {
            if ((this.CalcularSomaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CalcularSomaCompleted(this, new CalcularSomaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CalcularSomaAsync(int x, int y) {
            this.CalcularSomaAsync(x, y, null);
        }
        
        public void CalcularSomaAsync(int x, int y, object userState) {
            if ((this.onBeginCalcularSomaDelegate == null)) {
                this.onBeginCalcularSomaDelegate = new BeginOperationDelegate(this.OnBeginCalcularSoma);
            }
            if ((this.onEndCalcularSomaDelegate == null)) {
                this.onEndCalcularSomaDelegate = new EndOperationDelegate(this.OnEndCalcularSoma);
            }
            if ((this.onCalcularSomaCompletedDelegate == null)) {
                this.onCalcularSomaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCalcularSomaCompleted);
            }
            base.InvokeAsync(this.onBeginCalcularSomaDelegate, new object[] {
                        x,
                        y}, this.onEndCalcularSomaDelegate, this.onCalcularSomaCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorBDResponse Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.AddGestorWsSoap.RegistarGestorBD(Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorBDRequest request) {
            return base.Channel.RegistarGestorBD(request);
        }
        
        public bool RegistarGestorBD(string emailGestor, string passwordGestor, string emailAdmin, string passwordAdmin) {
            Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorBDRequest inValue = new Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorBDRequest();
            inValue.Body = new Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorBDRequestBody();
            inValue.Body.emailGestor = emailGestor;
            inValue.Body.passwordGestor = passwordGestor;
            inValue.Body.emailAdmin = emailAdmin;
            inValue.Body.passwordAdmin = passwordAdmin;
            Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorBDResponse retVal = ((Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.AddGestorWsSoap)(this)).RegistarGestorBD(inValue);
            return retVal.Body.RegistarGestorBDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.AddGestorWsSoap.BeginRegistarGestorBD(Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorBDRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRegistarGestorBD(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginRegistarGestorBD(string emailGestor, string passwordGestor, string emailAdmin, string passwordAdmin, System.AsyncCallback callback, object asyncState) {
            Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorBDRequest inValue = new Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorBDRequest();
            inValue.Body = new Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorBDRequestBody();
            inValue.Body.emailGestor = emailGestor;
            inValue.Body.passwordGestor = passwordGestor;
            inValue.Body.emailAdmin = emailAdmin;
            inValue.Body.passwordAdmin = passwordAdmin;
            return ((Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.AddGestorWsSoap)(this)).BeginRegistarGestorBD(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorBDResponse Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.AddGestorWsSoap.EndRegistarGestorBD(System.IAsyncResult result) {
            return base.Channel.EndRegistarGestorBD(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndRegistarGestorBD(System.IAsyncResult result) {
            Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorBDResponse retVal = ((Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.AddGestorWsSoap)(this)).EndRegistarGestorBD(result);
            return retVal.Body.RegistarGestorBDResult;
        }
        
        private System.IAsyncResult OnBeginRegistarGestorBD(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string emailGestor = ((string)(inValues[0]));
            string passwordGestor = ((string)(inValues[1]));
            string emailAdmin = ((string)(inValues[2]));
            string passwordAdmin = ((string)(inValues[3]));
            return this.BeginRegistarGestorBD(emailGestor, passwordGestor, emailAdmin, passwordAdmin, callback, asyncState);
        }
        
        private object[] OnEndRegistarGestorBD(System.IAsyncResult result) {
            bool retVal = this.EndRegistarGestorBD(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRegistarGestorBDCompleted(object state) {
            if ((this.RegistarGestorBDCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RegistarGestorBDCompleted(this, new RegistarGestorBDCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RegistarGestorBDAsync(string emailGestor, string passwordGestor, string emailAdmin, string passwordAdmin) {
            this.RegistarGestorBDAsync(emailGestor, passwordGestor, emailAdmin, passwordAdmin, null);
        }
        
        public void RegistarGestorBDAsync(string emailGestor, string passwordGestor, string emailAdmin, string passwordAdmin, object userState) {
            if ((this.onBeginRegistarGestorBDDelegate == null)) {
                this.onBeginRegistarGestorBDDelegate = new BeginOperationDelegate(this.OnBeginRegistarGestorBD);
            }
            if ((this.onEndRegistarGestorBDDelegate == null)) {
                this.onEndRegistarGestorBDDelegate = new EndOperationDelegate(this.OnEndRegistarGestorBD);
            }
            if ((this.onRegistarGestorBDCompletedDelegate == null)) {
                this.onRegistarGestorBDCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRegistarGestorBDCompleted);
            }
            base.InvokeAsync(this.onBeginRegistarGestorBDDelegate, new object[] {
                        emailGestor,
                        passwordGestor,
                        emailAdmin,
                        passwordAdmin}, this.onEndRegistarGestorBDDelegate, this.onRegistarGestorBDCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorUsingAPIResponse Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.AddGestorWsSoap.RegistarGestorUsingAPI(Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorUsingAPIRequest request) {
            return base.Channel.RegistarGestorUsingAPI(request);
        }
        
        public string RegistarGestorUsingAPI(string email, string password) {
            Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorUsingAPIRequest inValue = new Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorUsingAPIRequest();
            inValue.Body = new Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorUsingAPIRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorUsingAPIResponse retVal = ((Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.AddGestorWsSoap)(this)).RegistarGestorUsingAPI(inValue);
            return retVal.Body.RegistarGestorUsingAPIResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.AddGestorWsSoap.BeginRegistarGestorUsingAPI(Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorUsingAPIRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRegistarGestorUsingAPI(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginRegistarGestorUsingAPI(string email, string password, System.AsyncCallback callback, object asyncState) {
            Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorUsingAPIRequest inValue = new Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorUsingAPIRequest();
            inValue.Body = new Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorUsingAPIRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.AddGestorWsSoap)(this)).BeginRegistarGestorUsingAPI(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorUsingAPIResponse Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.AddGestorWsSoap.EndRegistarGestorUsingAPI(System.IAsyncResult result) {
            return base.Channel.EndRegistarGestorUsingAPI(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndRegistarGestorUsingAPI(System.IAsyncResult result) {
            Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.RegistarGestorUsingAPIResponse retVal = ((Monitum_SOAP_Client.ServiceReferenceAddGestorWsAsync.AddGestorWsSoap)(this)).EndRegistarGestorUsingAPI(result);
            return retVal.Body.RegistarGestorUsingAPIResult;
        }
        
        private System.IAsyncResult OnBeginRegistarGestorUsingAPI(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string email = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return this.BeginRegistarGestorUsingAPI(email, password, callback, asyncState);
        }
        
        private object[] OnEndRegistarGestorUsingAPI(System.IAsyncResult result) {
            string retVal = this.EndRegistarGestorUsingAPI(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRegistarGestorUsingAPICompleted(object state) {
            if ((this.RegistarGestorUsingAPICompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RegistarGestorUsingAPICompleted(this, new RegistarGestorUsingAPICompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RegistarGestorUsingAPIAsync(string email, string password) {
            this.RegistarGestorUsingAPIAsync(email, password, null);
        }
        
        public void RegistarGestorUsingAPIAsync(string email, string password, object userState) {
            if ((this.onBeginRegistarGestorUsingAPIDelegate == null)) {
                this.onBeginRegistarGestorUsingAPIDelegate = new BeginOperationDelegate(this.OnBeginRegistarGestorUsingAPI);
            }
            if ((this.onEndRegistarGestorUsingAPIDelegate == null)) {
                this.onEndRegistarGestorUsingAPIDelegate = new EndOperationDelegate(this.OnEndRegistarGestorUsingAPI);
            }
            if ((this.onRegistarGestorUsingAPICompletedDelegate == null)) {
                this.onRegistarGestorUsingAPICompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRegistarGestorUsingAPICompleted);
            }
            base.InvokeAsync(this.onBeginRegistarGestorUsingAPIDelegate, new object[] {
                        email,
                        password}, this.onEndRegistarGestorUsingAPIDelegate, this.onRegistarGestorUsingAPICompletedDelegate, userState);
        }
    }
}
