//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitum_SOAP_Client.ServiceReferenceAddGestorWs {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ipca.pt/", ConfigurationName="ServiceReferenceAddGestorWs.AddGestorWsSoap")]
    public interface AddGestorWsSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://ipca.pt/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ipca.pt/HelloWorld", ReplyAction="*")]
        Monitum_SOAP_Client.ServiceReferenceAddGestorWs.HelloWorldResponse HelloWorld(Monitum_SOAP_Client.ServiceReferenceAddGestorWs.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ipca.pt/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Monitum_SOAP_Client.ServiceReferenceAddGestorWs.HelloWorldResponse> HelloWorldAsync(Monitum_SOAP_Client.ServiceReferenceAddGestorWs.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ipca.pt/CalcularSoma", ReplyAction="*")]
        int CalcularSoma(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ipca.pt/CalcularSoma", ReplyAction="*")]
        System.Threading.Tasks.Task<int> CalcularSomaAsync(int x, int y);
        
        // CODEGEN: Generating message contract since element name emailGestor from namespace http://ipca.pt/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ipca.pt/RegistarGestorBD", ReplyAction="*")]
        Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorBDResponse RegistarGestorBD(Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorBDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ipca.pt/RegistarGestorBD", ReplyAction="*")]
        System.Threading.Tasks.Task<Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorBDResponse> RegistarGestorBDAsync(Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorBDRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://ipca.pt/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ipca.pt/RegistarGestorUsingAPI", ReplyAction="*")]
        Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorUsingAPIResponse RegistarGestorUsingAPI(Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorUsingAPIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ipca.pt/RegistarGestorUsingAPI", ReplyAction="*")]
        System.Threading.Tasks.Task<Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorUsingAPIResponse> RegistarGestorUsingAPIAsync(Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorUsingAPIRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://ipca.pt/", Order=0)]
        public Monitum_SOAP_Client.ServiceReferenceAddGestorWs.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Monitum_SOAP_Client.ServiceReferenceAddGestorWs.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://ipca.pt/", Order=0)]
        public Monitum_SOAP_Client.ServiceReferenceAddGestorWs.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Monitum_SOAP_Client.ServiceReferenceAddGestorWs.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ipca.pt/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistarGestorBDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistarGestorBD", Namespace="http://ipca.pt/", Order=0)]
        public Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorBDRequestBody Body;
        
        public RegistarGestorBDRequest() {
        }
        
        public RegistarGestorBDRequest(Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorBDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ipca.pt/")]
    public partial class RegistarGestorBDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string emailGestor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string passwordGestor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string emailAdmin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string passwordAdmin;
        
        public RegistarGestorBDRequestBody() {
        }
        
        public RegistarGestorBDRequestBody(string emailGestor, string passwordGestor, string emailAdmin, string passwordAdmin) {
            this.emailGestor = emailGestor;
            this.passwordGestor = passwordGestor;
            this.emailAdmin = emailAdmin;
            this.passwordAdmin = passwordAdmin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistarGestorBDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistarGestorBDResponse", Namespace="http://ipca.pt/", Order=0)]
        public Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorBDResponseBody Body;
        
        public RegistarGestorBDResponse() {
        }
        
        public RegistarGestorBDResponse(Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorBDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ipca.pt/")]
    public partial class RegistarGestorBDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RegistarGestorBDResult;
        
        public RegistarGestorBDResponseBody() {
        }
        
        public RegistarGestorBDResponseBody(bool RegistarGestorBDResult) {
            this.RegistarGestorBDResult = RegistarGestorBDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistarGestorUsingAPIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistarGestorUsingAPI", Namespace="http://ipca.pt/", Order=0)]
        public Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorUsingAPIRequestBody Body;
        
        public RegistarGestorUsingAPIRequest() {
        }
        
        public RegistarGestorUsingAPIRequest(Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorUsingAPIRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ipca.pt/")]
    public partial class RegistarGestorUsingAPIRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public RegistarGestorUsingAPIRequestBody() {
        }
        
        public RegistarGestorUsingAPIRequestBody(string email, string password) {
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistarGestorUsingAPIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistarGestorUsingAPIResponse", Namespace="http://ipca.pt/", Order=0)]
        public Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorUsingAPIResponseBody Body;
        
        public RegistarGestorUsingAPIResponse() {
        }
        
        public RegistarGestorUsingAPIResponse(Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorUsingAPIResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ipca.pt/")]
    public partial class RegistarGestorUsingAPIResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RegistarGestorUsingAPIResult;
        
        public RegistarGestorUsingAPIResponseBody() {
        }
        
        public RegistarGestorUsingAPIResponseBody(string RegistarGestorUsingAPIResult) {
            this.RegistarGestorUsingAPIResult = RegistarGestorUsingAPIResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AddGestorWsSoapChannel : Monitum_SOAP_Client.ServiceReferenceAddGestorWs.AddGestorWsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddGestorWsSoapClient : System.ServiceModel.ClientBase<Monitum_SOAP_Client.ServiceReferenceAddGestorWs.AddGestorWsSoap>, Monitum_SOAP_Client.ServiceReferenceAddGestorWs.AddGestorWsSoap {
        
        public AddGestorWsSoapClient() {
        }
        
        public AddGestorWsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddGestorWsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddGestorWsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddGestorWsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Monitum_SOAP_Client.ServiceReferenceAddGestorWs.HelloWorldResponse Monitum_SOAP_Client.ServiceReferenceAddGestorWs.AddGestorWsSoap.HelloWorld(Monitum_SOAP_Client.ServiceReferenceAddGestorWs.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Monitum_SOAP_Client.ServiceReferenceAddGestorWs.HelloWorldRequest inValue = new Monitum_SOAP_Client.ServiceReferenceAddGestorWs.HelloWorldRequest();
            inValue.Body = new Monitum_SOAP_Client.ServiceReferenceAddGestorWs.HelloWorldRequestBody();
            Monitum_SOAP_Client.ServiceReferenceAddGestorWs.HelloWorldResponse retVal = ((Monitum_SOAP_Client.ServiceReferenceAddGestorWs.AddGestorWsSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Monitum_SOAP_Client.ServiceReferenceAddGestorWs.HelloWorldResponse> Monitum_SOAP_Client.ServiceReferenceAddGestorWs.AddGestorWsSoap.HelloWorldAsync(Monitum_SOAP_Client.ServiceReferenceAddGestorWs.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Monitum_SOAP_Client.ServiceReferenceAddGestorWs.HelloWorldResponse> HelloWorldAsync() {
            Monitum_SOAP_Client.ServiceReferenceAddGestorWs.HelloWorldRequest inValue = new Monitum_SOAP_Client.ServiceReferenceAddGestorWs.HelloWorldRequest();
            inValue.Body = new Monitum_SOAP_Client.ServiceReferenceAddGestorWs.HelloWorldRequestBody();
            return ((Monitum_SOAP_Client.ServiceReferenceAddGestorWs.AddGestorWsSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public int CalcularSoma(int x, int y) {
            return base.Channel.CalcularSoma(x, y);
        }
        
        public System.Threading.Tasks.Task<int> CalcularSomaAsync(int x, int y) {
            return base.Channel.CalcularSomaAsync(x, y);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorBDResponse Monitum_SOAP_Client.ServiceReferenceAddGestorWs.AddGestorWsSoap.RegistarGestorBD(Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorBDRequest request) {
            return base.Channel.RegistarGestorBD(request);
        }
        
        public bool RegistarGestorBD(string emailGestor, string passwordGestor, string emailAdmin, string passwordAdmin) {
            Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorBDRequest inValue = new Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorBDRequest();
            inValue.Body = new Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorBDRequestBody();
            inValue.Body.emailGestor = emailGestor;
            inValue.Body.passwordGestor = passwordGestor;
            inValue.Body.emailAdmin = emailAdmin;
            inValue.Body.passwordAdmin = passwordAdmin;
            Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorBDResponse retVal = ((Monitum_SOAP_Client.ServiceReferenceAddGestorWs.AddGestorWsSoap)(this)).RegistarGestorBD(inValue);
            return retVal.Body.RegistarGestorBDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorBDResponse> Monitum_SOAP_Client.ServiceReferenceAddGestorWs.AddGestorWsSoap.RegistarGestorBDAsync(Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorBDRequest request) {
            return base.Channel.RegistarGestorBDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorBDResponse> RegistarGestorBDAsync(string emailGestor, string passwordGestor, string emailAdmin, string passwordAdmin) {
            Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorBDRequest inValue = new Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorBDRequest();
            inValue.Body = new Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorBDRequestBody();
            inValue.Body.emailGestor = emailGestor;
            inValue.Body.passwordGestor = passwordGestor;
            inValue.Body.emailAdmin = emailAdmin;
            inValue.Body.passwordAdmin = passwordAdmin;
            return ((Monitum_SOAP_Client.ServiceReferenceAddGestorWs.AddGestorWsSoap)(this)).RegistarGestorBDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorUsingAPIResponse Monitum_SOAP_Client.ServiceReferenceAddGestorWs.AddGestorWsSoap.RegistarGestorUsingAPI(Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorUsingAPIRequest request) {
            return base.Channel.RegistarGestorUsingAPI(request);
        }
        
        public string RegistarGestorUsingAPI(string email, string password) {
            Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorUsingAPIRequest inValue = new Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorUsingAPIRequest();
            inValue.Body = new Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorUsingAPIRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorUsingAPIResponse retVal = ((Monitum_SOAP_Client.ServiceReferenceAddGestorWs.AddGestorWsSoap)(this)).RegistarGestorUsingAPI(inValue);
            return retVal.Body.RegistarGestorUsingAPIResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorUsingAPIResponse> Monitum_SOAP_Client.ServiceReferenceAddGestorWs.AddGestorWsSoap.RegistarGestorUsingAPIAsync(Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorUsingAPIRequest request) {
            return base.Channel.RegistarGestorUsingAPIAsync(request);
        }
        
        public System.Threading.Tasks.Task<Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorUsingAPIResponse> RegistarGestorUsingAPIAsync(string email, string password) {
            Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorUsingAPIRequest inValue = new Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorUsingAPIRequest();
            inValue.Body = new Monitum_SOAP_Client.ServiceReferenceAddGestorWs.RegistarGestorUsingAPIRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((Monitum_SOAP_Client.ServiceReferenceAddGestorWs.AddGestorWsSoap)(this)).RegistarGestorUsingAPIAsync(inValue);
        }
    }
}
